[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints= {sepolia-eth = "your-address", arb-sepolia = "your-address"}

remappings = ['@openzeppelin/=lib/openzeppelin-contracts','@chainlink/=lib/chainlink-brownie-contracts',
'@ccip/=lib/ccip/',
'@chainlink-local/=lib/chainlink-local',
]

[fuzz]
runs = 1024
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
